name: Android Build

on:
  push:
    branches: [ "main", "master" ]
    tags:
      - 'v*' # Запускать релиз при пуше тегов, начинающихся с "v" (например, v1.0, v1.1)
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch: # Позволяет запускать сборку вручную

# Даем права на создание релизов
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug
      env:
        COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}

    - name: Upload APK as Artifact (Обычная сборка)
      uses: actions/upload-artifact@v4
      with:
        name: KB_Learning_APK
        path: composeApp/build/outputs/apk/debug/*.apk
        
    - name: Create GitHub Release (Только при тегах v*)
      # Этот шаг выполнится ТОЛЬКО если вы запушили тег v1.0, v1.1 и т.д.
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        # Автоматически сгенерирует список коммитов с момента прошлого релиза
        generate_release_notes: true 
        files: composeApp/build/outputs/apk/debug/*.apk
